### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ipmsteven** [xmfun/xmfun#1]
@pololee Just some rough ideas
- [ ] https://github.com/ipmsteven/xmfun/pull/7/files and add -d / -u support?
- [x] abroad support
- [ ] DSL support ?https://github.com/dazuma/blockenspiel
- [ ] **terminal** text ui [playa](https://github.com/gavinlaking/playa)
- [x] support multiple type
- [x] code refactoring
- [x] test,test test(unit test through different rubies)
- [x] Make it a gem
- [x] set up CI, Build Status,
- [x] Gem Version,  
- [x] Code Climate, 
- [x] Dependency Status, 
- [x] Gitter chat 
- [x] xmfun.github.io
- [x] http persisted connection [https://github.com/rubygems/rubygems-mirror]
- [x] refine progress bar for single song download (based on downloaded percentage)
- [x] chruby 1.9  in my local env (gemspec issue) [I switched to rvm finally]
- [x] make Xmfun::Util::Decoder better @pololee 
- [x] test xmfun update
- [ ] check md5 hash in features mp3 download
